version: 2

updates:
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'javascript'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      bun-dependencies:
        applies-to: version-updates
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      github-actions-dependencies:
        applies-to: version-updates
        patterns:
          - '*'
