services:
  dev:
    build:
      context: .
      target: base
    command: ['bun', 'x', 'rsbuild', 'dev']
    restart: unless-stopped
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
      - '6006:6006'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://${WEBSITE_DOMAIN}:${DEV_PORT}']
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 90s
    networks:
      - crm-network
  rca:
    profiles: [tools]
    build:
      context: .
      target: rca
    volumes:
      - .:/app

networks:
  crm-network:
    external: true
    name: crm-network
volumes:
  node_modules:
