services:
  dev:
    build:
      context: .
      target: base
    command: ['./node_modules/.bin/craco', 'start']
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://${WEBSITE_DOMAIN}:${DEV_PORT}']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
