services:
  dev:
    build:
      context: .
      target: base
    command: ['./node_modules/.bin/craco', 'start']
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - '3000:3000'
      - "6006:6006"
    healthcheck:
      test: ['CMD-SHELL', 'curl -fsS http://localhost:${DEV_PORT} || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
