services:
  memory-leak:
    build:
      context: .
      dockerfile: MemoryLeak.Dockerfile
      target: final
    environment:
      - DISPLAY=:99
      - PUPPETEER_DISABLE_HEADLESS_WARNING=1
      - REACT_APP_PROD_CONTAINER_API_URL=http://prod:3001
      - REACT_APP_PROD_HOST_API_URL=http://localhost:3001
      - MEMLAB_DEBUG=true
      - MEMLAB_SKIP_WARMUP=true
      - REACT_APP_CONTINUOUS_DEPLOYMENT_HEADER_NAME=no-aws-header-name
      - REACT_APP_CONTINUOUS_DEPLOYMENT_HEADER_VALUE=no-aws-header-value
      - NODE_ENV=production
    init: true
    shm_size: '1gb'
    networks:
      - website-network
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
      test: ['CMD', 'chromium-browser', '--version']

networks:
  website-network:
    external: true
    name: website-network
