const TOKENS = Object.freeze({
  LoginAPI: Symbol('LoginAPI'),
  RegistrationAPI: Symbol('RegistrationAPI'),
  ApolloClient: Symbol('ApolloClient'),
  HttpsClient: Symbol('HttpsClient'),
  ApiErrorFactory: Symbol('ApiErrorFactory'),
  ApiStatusErrorFactory: Symbol('ApiStatusErrorFactory'),
  HttpErrorGuard: Symbol('HttpErrorGuard'),
  ErrorParser: Symbol('ErrorParser'),
  ErrorHandler: Symbol('ErrorHandler'),
  AuthErrorHandler: Symbol('AuthErrorHandler'),
  AuthRequestErrors: Symbol('AuthRequestErrors'),
  GraphQLUrl: Symbol('GraphQLUrl'),
  LoginResponseMapper: Symbol('LoginResponseMapper'),
  RegistrationResponseMapper: Symbol('RegistrationResponseMapper'),
  AuthUiErrorMapper: Symbol('AuthUiErrorMapper'),
  HttpRequestConfigBuilder: Symbol('HttpRequestConfigBuilder'),
  HttpResponseProcessor: Symbol('HttpResponseProcessor'),
  HttpErrorResponseParser: Symbol('HttpErrorResponseParser'),
  HttpClientFactory: Symbol('HttpClientFactory'),
  AbortErrorDetector: Symbol('AbortErrorDetector'),
  AuthRepository: Symbol('AuthRepository'),
  AuthRepositoryDeps: Symbol('AuthRepositoryDeps'),
} as const);

export default TOKENS;
