FROM golang:1.25.8-alpine3.22 AS builder

WORKDIR /app

ENV CGO_ENABLED 0

RUN apk add --no-cache git

RUN go install go.k6.io/xk6/cmd/xk6@v0.18.0

RUN xk6 build \
    --with github.com/grafana/xk6-faker@v0.4.1 \
    --with github.com/grafana/xk6-exec@v0.5.0 \
    --with github.com/avitalique/xk6-file@v1.5.0

FROM alpine:3.22
RUN apk add --no-cache ca-certificates tzdata

COPY --from=builder /app/k6 /bin/

RUN addgroup -g 1000 k6 && adduser -u 1000 -G k6 -D k6 \
    && chown k6:k6 /bin/k6 \
    && mkdir -p /loadTests/results \
    && chown k6:k6 /loadTests/results

USER k6

ENTRYPOINT [ "k6" ]
