#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm format
pnpm lint:eslint && git diff --name-only main | grep -E "(.js$|.ts$|.tsx$)"
pnpm lint:tsc --noEmit
pnpm lint:md && git diff --name-only main | grep -E "(.md$)"
pnpm test:unit --passWithNoTests $(git diff --cached --name-only | grep '.ts$')
