name: dependency cruiser
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  dependency-cruiser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Start container
        run: make start

      - name: Run dependency cruiser
        run: make lint-deps
