name: e2e testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js and install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install
        working-directory: .

      - name: Build
        run: pnpm run build

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install Cypress binary
        run: pnpm exec cypress install

      - name: Start dev server
        run: nohup pnpm run dev > dev-server.log 2>&1 &

      - name: Wait for dev server to start
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests
        run: pnpm run test:e2e
