name: performance testing

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  performance:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Build dev image with Chromium
        run: INSTALL_CHROMIUM=true make build-dev-chromium

      - name: Start container
        run: INSTALL_CHROMIUM=true make start

      - name: Run desktop performance test
        run: make lighthouse-desktop

      - name: Run mobile performance test
        run: make lighthouse-mobile
