name: static testing

on:
  pull_request:
    branches: ['main']

jobs:
  static:
    runs-on: ubuntu-latest
    env:
      CI: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Cache pnpm dependencies
        id: cache-pnpm-dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: make install
        if: |
          steps.cache-pnpm-dependencies.outputs.cache-hit != 'true' ||
          steps.cache-pnpm-dependencies.outputs.cache-hit != 'true'

      - name: Run all linters
        run: make lint
