name: visual tests

on:
  pull_request:
    branches:
      - main

jobs:
  visual-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run visual tests
        continue-on-error: true
        run: |
          make test-visual || echo "Tests completed with errors"

      - name: Ensure reports are copied
        if: always()
        run: |          
          docker compose -f docker-compose.test.yml exec playwright sh -c "cp -r /tmp/playwright-report /app/ 2>/dev/null || echo 'No reports to copy'" || true
          docker compose -f docker-compose.test.yml exec playwright sh -c "cp -r /tmp/test-results /app/ 2>/dev/null || echo 'No test results to copy'" || true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
          if-no-files-found: warn