name: visual tests

on:
  pull_request:
    branches:
      - main

jobs:
  visual-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run visual tests
        id: visual-tests
        run: |
          make test-visual
        continue-on-error: true

      - name: Upload Playwright Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
          if-no-files-found: warn

      - name: Check visual test results
        if: steps.visual-tests.outcome == 'failure'
        run: |
          echo "❌ Visual tests failed. Check the uploaded reports for details."
          echo "📊 Reports are available in the 'Artifacts' section below."
          exit 1
